# _config.yml

title: "Occupancy Estimation"
description: "A project analyzing sensor data to estimate study room occupancy using multivariate statistical methods."
url: "https://leemabhena.github.io/room_occupancy/"
author: "Lee Mabhena"

# Use the minimal-mistakes theme
# remote_theme: "mmistakes/minimal-mistakes@4.24.0" # Specify the version for consistency
theme: minima

# remote_theme: pages-themes/hacker@v0.2.0

# Plugins (GitHub Pages supports these plugins)
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Navigation Menu
header_pages:
  - data.md
  - methodology.md

# Build settings
markdown: kramdown
highlighter: rouge


# Exclude folders from the build
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"

future: true
